# Generated by Django 2.0.7 on 2018-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180723_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.SmallIntegerField(choices=[(1, '办公室'), (2, '裁剪组'), (3, '缝纫组'), (4, '熨烫组'), (5, '包装组'), (6, '运输组'), (7, '日工')], default=0, help_text='部门', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='家庭住址', max_length=100, null=True, verbose_name='家庭住址'),
        ),
    ]
