# Generated by Django 2.0.7 on 2018-07-28 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('products', '0002_auto_20180728_2202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtailor',
            name='user',
            field=models.ForeignKey(help_text='姓名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='recordsew',
            name='productBid',
            field=models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='products.ProductBid', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='recordsew',
            name='user',
            field=models.ForeignKey(help_text='姓名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='recordoutput',
            name='product',
            field=models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='recordiron',
            name='productBid',
            field=models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='products.ProductBid', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='recordiron',
            name='user',
            field=models.ForeignKey(help_text='姓名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名'),
        ),
    ]
