# Generated by Django 2.0.7 on 2018-07-30 07:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_num', models.CharField(max_length=6, verbose_name='产品编号')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('describe', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品描述')),
                ('tailor_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='裁剪价格')),
                ('sew_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='缝纫价格')),
                ('iron_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='熨烫价格')),
                ('packag_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='包装价格')),
                ('status', models.SmallIntegerField(choices=[(0, '未上市'), (1, '热销中'), (2, '已下市')], default=0, help_text='0 未上市 1 热销中 2 已下市', verbose_name='状态')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_num', models.IntegerField(help_text='数量状态', verbose_name='数量状态')),
                ('number', models.IntegerField(help_text='数量', verbose_name='数量')),
                ('remainingNumberSew', models.IntegerField(help_text='未缝纫数量', verbose_name='未缝纫数量')),
                ('remainingNumberIron', models.IntegerField(help_text='未熨烫（入库）数量', verbose_name='未熨烫（入库）数量')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, help_text='时间', verbose_name='时间')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '产品标',
                'verbose_name_plural': '产品标',
                'db_table': 'products_bid',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类', max_length=12, verbose_name='分类')),
                ('remark', models.CharField(help_text='分类描述', max_length=50, verbose_name='分类描述')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='库存数量', verbose_name='库存数量')),
                ('updated_time', models.DateField(auto_now=True, help_text='最后更新时间', verbose_name='最后更新时间')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品库存',
                'verbose_name_plural': '产品库存',
                'db_table': 'products_inventory',
            },
        ),
    ]
