# Generated by Django 2.0.7 on 2018-07-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbid',
            name='recordTailor',
            field=models.OneToOneField(help_text='关联裁剪记录', on_delete=django.db.models.deletion.CASCADE, to='records.RecordTailor', verbose_name='关联裁剪记录'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='分类'),
        ),
    ]
