# Generated by Django 2.0.7 on 2018-07-25 08:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bz_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='包装价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cj_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='裁剪价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fr_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='缝纫价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_num',
            field=models.CharField(max_length=6, verbose_name='产品编号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='上次修改时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='yt_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='熨烫价格'),
        ),
    ]
