# Generated by Django 2.0.7 on 2018-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180728_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbid',
            name='number',
            field=models.IntegerField(default=0, help_text='数量', verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbid',
            name='status_num',
            field=models.IntegerField(default=0, help_text='数量状态', verbose_name='数量状态'),
            preserve_default=False,
        ),
    ]
