# Generated by Django 2.0.7 on 2018-07-30 07:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='月薪资', max_digits=20, verbose_name='月薪资')),
                ('month', models.CharField(help_text='月份', max_length=10, verbose_name='月份')),
                ('status', models.SmallIntegerField(choices=[(0, '未发放'), (1, '已发放')], default=0, help_text='状态', verbose_name='状态')),
            ],
            options={
                'verbose_name': '应发工资',
                'verbose_name_plural': '应发工资',
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='SalaryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='金额', max_digits=20, verbose_name='金额')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, help_text='时间', verbose_name='时间')),
                ('status', models.SmallIntegerField(choices=[(0, '未统计'), (1, '已统计')], default=0, help_text='状态', verbose_name='状态')),
                ('recordIron', models.ForeignKey(blank=True, help_text='关联记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='records.RecordIron', verbose_name='关联记录')),
                ('recordSew', models.ForeignKey(blank=True, help_text='关联记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='records.RecordSew', verbose_name='关联记录')),
                ('recordTailor', models.ForeignKey(blank=True, help_text='关联记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='records.RecordTailor', verbose_name='关联记录')),
            ],
            options={
                'verbose_name': '工资记录',
                'verbose_name_plural': '工资记录',
                'db_table': 'salary_list',
            },
        ),
    ]
