# Generated by Django 2.0.7 on 2018-07-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_auto_20180728_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarylist',
            name='inrecord',
            field=models.SmallIntegerField(default=1, help_text='关联入库记录的id', verbose_name='关联入库记录'),
            preserve_default=False,
        ),
    ]
