# Generated by Django 2.0.7 on 2018-07-29 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180728_2202'),
        ('salary', '0003_salarylist_inrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarylist',
            name='inrecord',
        ),
        migrations.AddField(
            model_name='salarylist',
            name='recordiron',
            field=models.ForeignKey(blank=True, help_text='关联记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='records.RecordIron', verbose_name='关联记录'),
        ),
        migrations.AddField(
            model_name='salarylist',
            name='recordsew',
            field=models.ForeignKey(blank=True, help_text='关联记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='records.RecordSew', verbose_name='关联记录'),
        ),
        migrations.AddField(
            model_name='salarylist',
            name='recordtailor',
            field=models.ForeignKey(blank=True, help_text='关联记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='records.RecordTailor', verbose_name='关联记录'),
        ),
    ]
