# Generated by Django 2.0.7 on 2018-07-23 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_number', models.IntegerField(default=0, help_text='状态 / 已经入库数量', verbose_name='状态 / 已经入库数量')),
                ('number', models.IntegerField(help_text='数量', verbose_name='数量')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, help_text='时间', verbose_name='时间')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='产品')),
                ('user', models.ForeignKey(help_text='姓名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '入库管理',
                'verbose_name_plural': '入库管理',
                'db_table': 'inventory_in_record',
            },
        ),
        migrations.CreateModel(
            name='OutRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_number', models.IntegerField(default=0, help_text='状态 / 已经入库数量', verbose_name='状态 / 已经入库数量')),
                ('number', models.IntegerField(help_text='数量', verbose_name='数量')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, help_text='时间', verbose_name='时间')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '出库管理',
                'verbose_name_plural': '出库管理',
                'db_table': 'inventory_out_record',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='库存数量', verbose_name='库存数量')),
                ('updated_time', models.DateField(auto_now=True, help_text='最后更新时间', verbose_name='最后更新时间')),
                ('product', models.ForeignKey(help_text='产品', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '仓库库存',
                'verbose_name_plural': '仓库库存',
                'db_table': 'inventory_warehouse',
            },
        ),
    ]
